/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Cuenta;
import controlador.Controlador;

/**
 *
 * @author leopoldomorales
 */
public class Menu extends javax.swing.JFrame {

    
    public static int indexRow = -1;
    
    public static Cuenta cuenta;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        limpiarTextFields();
        Controlador.crearUsuarios();
        dibujarUsuariosEnLaTabla();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        mostrarTodosButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        direccionLabel = new javax.swing.JLabel();
        emaiLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        telefonoLabel = new javax.swing.JLabel();
        numeroCuentaLabel = new javax.swing.JLabel();
        numeroCuentaTextField = new javax.swing.JTextField();
        saldoCuentaLabel = new javax.swing.JLabel();
        saldoTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable = new javax.swing.JTable();
        buscarNumeroCuentaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mensajeLabel = new javax.swing.JLabel();
        limpiarFiltroButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrarButton.setText("Registrar Nuevo Cliente");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });

        buscarButton.setText("Buscar Cliente");
        buscarButton.setPreferredSize(new java.awt.Dimension(167, 23));
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar Cliente");
        eliminarButton.setPreferredSize(new java.awt.Dimension(108, 23));

        mostrarTodosButton.setText("Mostrar todos los clientes");

        editarButton.setText("Editar Cliente");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        nombreLabel.setText("NOMBRE:");

        direccionLabel.setText("DIRECCIÓN:");

        emaiLabel.setText("EMAIL:");

        telefonoLabel.setText("TELÉFONO:");

        numeroCuentaLabel.setText("NUMERO CUENTA:");

        saldoCuentaLabel.setText("SALDO:");

        myTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"11", "11", "11", "11", "11", "11", "1"}
            },
            new String [] {
                "ID", "Numero De Cuenta", "Nombre", "Email", "Dirección", "Teléfono", "Saldo"
            }
        ));
        myTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        myTable.getTableHeader().setReorderingAllowed(false);
        myTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(myTable);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("NUMERO DE CUENTA:");

        mensajeLabel.setText("jLabel3");

        limpiarFiltroButton.setText("Limpiar filtro");
        limpiarFiltroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarFiltroButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarNumeroCuentaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(eliminarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mostrarTodosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(limpiarFiltroButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(numeroCuentaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(numeroCuentaTextField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(saldoCuentaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mensajeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(registrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limpiarFiltroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarNumeroCuentaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrarTodosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreLabel)
                    .addComponent(telefonoLabel)
                    .addComponent(emaiLabel)
                    .addComponent(direccionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(numeroCuentaLabel)
                        .addGap(2, 2, 2)
                        .addComponent(numeroCuentaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saldoCuentaLabel)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensajeLabel))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
        
        String id = idTextField.getText();
        String nombre = nombreTextField.getText();
        String direccion = direccionTextField.getText();
        String email = emailTextField.getText();
        String telefono = telefonoTextField.getText();
        String numeroCuenta = numeroCuentaTextField.getText();
        String saldo = saldoTextField.getText();
        String datosClienteArray[] = {id,nombre,direccion,email,numeroCuenta,saldo,telefono};
        
  
        if(hayDatosSinLlenar(datosClienteArray)){
            mostrarMensaje("Error","Por favor llena todos los datos");
        }else{
            //Voy a revisar si los datos cumplen con los requerimientos 
              if(id.length()>=4){ //1.- Tamaño ID
                   try{
                        int numeroCuentaInt = Integer.parseInt(numeroCuenta);
                        double saldoDouble = Double.parseDouble(saldo);
                       
                        if(Controlador.datosRepetidos(id, email, numeroCuentaInt)){  //2.- No estén repetidos
                            System.out.println("Datos repetidos, intenta con otros");
                            String titulo = "Error";
                            String descripcion = "id, emial o número de cuenta repetidos";
                            mostrarMensaje(titulo, descripcion);
                            
                        }else{
                            Controlador.registrarCliente(id,nombre,direccion,telefono,numeroCuentaInt, saldoDouble, email);
                            mensajeLabel.setText("Usuario registrado exitosamente!!!");
                            limpiarTextFields();
                            dibujarUsuariosEnLaTabla();
                        }

                        
                    }catch(Exception e){
                        System.out.println("Error al intentar registrar el cliente por el saldo o el numero de cuenta");
                    }
                  
              }else
                  mostrarMensaje("Error", "ID incorrecto, debe de contener 4 caractéres");   
        }
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        String numeroDeCuentaBuscada = buscarNumeroCuentaTextField.getText();
        String numeroCuentaBuscadaArray[] = {numeroDeCuentaBuscada};
        
        if(hayDatosSinLlenar(numeroCuentaBuscadaArray)){
            mostrarMensaje("Error", "Ingresa una cuenta a buscar");
        }else{
        
            try {
                int numeroDeCuentaInt = Integer.parseInt(numeroDeCuentaBuscada);
                dibujarUsuarioBuscadoEnLaTabla(Controlador.buscarUsuario(numeroDeCuentaInt,"poblar"));
                
            } catch (Exception e) {
                mostrarMensaje("Error", "No es un número entero");
                
            }
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void limpiarFiltroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarFiltroButtonActionPerformed
        dibujarUsuariosEnLaTabla();
    }//GEN-LAST:event_limpiarFiltroButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
     
        if(indexRow!=-1){
            
            String numeroCuentaString = myTable.getValueAt(indexRow, 1).toString();
            
            try {
                int numeroCuentaInt = Integer.parseInt(numeroCuentaString);
                Controlador.buscarUsuario(numeroCuentaInt,"editar");
            } catch (Exception e) {
                mostrarMensaje("Error", "Error al intentar convertir el String a int");
            }
        }
       
    }//GEN-LAST:event_editarButtonActionPerformed

    
     
    /*obtengo la fila a partir de un punto del mouse (evt) 
    * indexRow es una variable global que la necesitaremos para el botón editar
    */
    private void myTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTableMouseClicked
       
        indexRow = myTable.rowAtPoint(evt.getPoint());
        
    }//GEN-LAST:event_myTableMouseClicked
    
    
    private boolean hayDatosSinLlenar(String datosClienteArray[]){
        
        for (String datoClienteArray : datosClienteArray) {
            if (datoClienteArray.equals("")) {
                return true;
            }
        }
        return false;
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField buscarNumeroCuentaTextField;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel emaiLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarFiltroButton;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JButton mostrarTodosButton;
    private javax.swing.JTable myTable;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel numeroCuentaLabel;
    private javax.swing.JTextField numeroCuentaTextField;
    private javax.swing.JButton registrarButton;
    private javax.swing.JLabel saldoCuentaLabel;
    private javax.swing.JTextField saldoTextField;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables

    

    private void limpiarTextFields() {
    
        idTextField.setText("");
        nombreTextField.setText("");
        direccionTextField.setText("");
        telefonoTextField.setText("");
        emailTextField.setText("");
        saldoTextField.setText("");
        numeroCuentaTextField.setText("");
        mensajeLabel.setText("");
        
        
        
    
    }

    

    

    private void mostrarMensaje(String titulo, String descripcion) {
        mensajeLabel.setText("");
        JOptionPane.showMessageDialog(this, descripcion, titulo, JOptionPane.ERROR_MESSAGE);
        
    }
    
    public void dibujarUsuariosEnLaTabla(){
      
       
        DefaultTableModel tableModel = (DefaultTableModel) myTable.getModel(); 
        
        tableModel.setRowCount(0); //limpiar la tabla 
        
        ArrayList<Cuenta> cuentas = Controlador.obtenerTodasLasCuentas();
        
        for (Cuenta cuenta : cuentas) {
            Object filaCuenta[] = new Object[7];
            
            filaCuenta[0] = cuenta.getId();
            filaCuenta[1] = cuenta.getNumeroCuenta();
            filaCuenta[2] = cuenta.getNombre();
            filaCuenta[3] = cuenta.getEmail();
            filaCuenta[4] = cuenta.getDireccion();
            filaCuenta[5] = cuenta.getTelefono();
            filaCuenta[6] = cuenta.getSaldo();
            tableModel.addRow(filaCuenta);
        }
        myTable = new JTable(tableModel);
    
    }
    
    public void dibujarUsuarioBuscadoEnLaTabla(Cuenta cuenta){
       
        DefaultTableModel tableModel = (DefaultTableModel) myTable.getModel(); 
        
        tableModel.setRowCount(0); //limpiar la tabla 
        

        Object filaCuenta[] = new Object[7];

        filaCuenta[0] = cuenta.getId();
        filaCuenta[1] = cuenta.getNumeroCuenta();
        filaCuenta[2] = cuenta.getNombre();
        filaCuenta[3] = cuenta.getEmail();
        filaCuenta[4] = cuenta.getDireccion();
        filaCuenta[5] = cuenta.getTelefono();
        filaCuenta[6] = cuenta.getSaldo();
        tableModel.addRow(filaCuenta);
        
        myTable = new JTable(tableModel);
    
    }
    
    
    
}
