/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.JRadioButton;
import modelo.CuentaAhorro;

/**
 *
 * @author leopoldomorales
 */
public class RegistrarView extends javax.swing.JFrame {
    
    public static CuentaAhorro cuentaAhorro;

    public int contadorDeClicks = 0;
    
    /**
     * Creates new form registrarView
     */
    public RegistrarView(String tituloBotonAceptar) {
        initComponents();
       
       registrarButton.setText(tituloBotonAceptar);
       
       //Es necesario para que la vista tenga un radio button seleccionado por 
       //defecto al cargar
        mensajeLabel.setText(" "); 
        desabilitarElementosDeLaVista();
        ahorroRadioButton.setSelected(true);
    }
    
    public RegistrarView(){
       
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        numeroCuentaTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ahorroRadioButton = new javax.swing.JRadioButton();
        inversionRadioButton = new javax.swing.JRadioButton();
        creditoRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        saldoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        limiteDeCreditoTextField = new javax.swing.JTextField();
        limiteCreditoLabel = new javax.swing.JLabel();
        interesMoratorioLabel = new javax.swing.JLabel();
        interesMoratorioTextField = new javax.swing.JTextField();
        interesInversionLabel = new javax.swing.JLabel();
        interesInversionTextField = new javax.swing.JTextField();
        mensajeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        registrarButton.setText("Registrar");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de cuenta");

        ahorroRadioButton.setText("Ahorro");
        ahorroRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        inversionRadioButton.setText("Inversión");
        inversionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        creditoRadioButton.setText("Crédito");
        creditoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de cuenta");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Teléfono:");

        jLabel5.setText("e-mail:");

        jLabel6.setText("Saldo:");

        jLabel7.setText("Nombre Completo:");

        limiteCreditoLabel.setText("Limite de crédito:");

        interesMoratorioLabel.setText("Interés moratorio");

        interesInversionLabel.setText("Interés inversión");

        mensajeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeLabel.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 199, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(interesInversionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(interesInversionTextField)
                            .addComponent(interesMoratorioTextField)
                            .addComponent(limiteDeCreditoTextField)
                            .addComponent(limiteCreditoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saldoTextField)
                            .addComponent(emailTextField)
                            .addComponent(telefonoTextField)
                            .addComponent(direccionTextField)
                            .addComponent(numeroCuentaTextField)
                            .addComponent(nombreTextField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(interesMoratorioLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registrarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ahorroRadioButton)
                        .addGap(54, 54, 54)
                        .addComponent(inversionRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(creditoRadioButton)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mensajeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ahorroRadioButton)
                    .addComponent(inversionRadioButton)
                    .addComponent(creditoRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroCuentaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limiteCreditoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limiteDeCreditoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interesMoratorioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interesMoratorioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interesInversionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interesInversionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(registrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MainView.botonesActivos = true;
    }//GEN-LAST:event_formWindowClosing

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        MainView.botonesActivos = true;
        dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
       String tipoDeCuenta = "";
       String nombre = nombreTextField.getText();
       String direccion = direccionTextField.getText();
       String telefono = telefonoTextField.getText();
       String email = emailTextField.getText();
       String saldo = saldoTextField.getText();
       String numeroDeCuenta = numeroCuentaTextField.getText();
       String limiteDeCredito = limiteDeCreditoTextField.getText();
       String interesInversion = interesMoratorioTextField.getText();
       String interesMoratorio = interesInversionTextField.getText();
       boolean creditoSeleccionado = creditoRadioButton.isSelected();
       boolean ahorroSeleccionado = ahorroRadioButton.isSelected();
       boolean inversionSeleccionado = inversionRadioButton.isSelected();
       
       
       if (creditoSeleccionado){
           tipoDeCuenta = "CREDITO";
       }else if ( ahorroSeleccionado){
           tipoDeCuenta = "AHORRO";
       }else if (inversionSeleccionado){
           tipoDeCuenta = "INVERSION";
       }
       
       
       /*
       
       Es necesario primero revisar que los datos no esten vacios y que se puedan "parsear"
       Despues debemos de revisar que tiepo de cuenta quiere registrar el usuario y mandar llamar a su
       método.... (antes tengo que crear el método en la clase controladora
       
       */
       
       
       
        //Revistar que no hay campos vacios
        try {
            int numeroCuentaInt = Integer.parseInt(numeroDeCuenta);
            double saldoDouble = Double.parseDouble(saldo);
            //double interesInversionDouble = Double.parseDouble(interesInversion);
            //double interesMoratorioDouble = Double.parseDouble(interesMoratorio);
            //double limiteDeCreditoDouble = Double.parseDouble(limiteDeCredito);
            //mandar llamar a registrar del controlador
            
          
                //Tenemos que revisar si vamos a registrar o a editar
                if (registrarButton.getText().equals("Registrar")) {
                     
                    if(!controlador.Controlador.numeroDeCuentaRepetido(numeroCuentaInt)){
                        if(controlador.Controlador.crearCuentaDeAhorros(tipoDeCuenta, nombre,  direccion,  email,  telefono,  numeroCuentaInt,  saldoDouble)){
                            limpiarDatosDelaVista();
                            mensajeLabel.setText("Usuario registrado exitosamente");
                            mensajeLabel.setForeground(Color.BLUE);
                            MainView.dibujarUsuariosEnLaTabla();
                            //Hace falta que se muestre una retroalimentación en la vista para que el usuario 
                            //sepa que ya se registró la cuenta
                        }else{
                            mensajeLabel.setText("Error al registrar");
                            mensajeLabel.setForeground(Color.RED);
                        }
                    }else{
                
                        mensajeLabel.setText("Numero de cuenta repetido");
                        mensajeLabel.setForeground(Color.RED);
                     }
                  

                }else {
                    //editar 
                    /*
                        Si el numero de cuenta nuevo y viejo son iguales no tengo que 
                        buscar si el numero de cuenta ya esta ocupado
                    */
                    if(numeroCuentaInt == cuentaAhorro.getNumeroCuenta()){
                        if(controlador.Controlador.editarCuentaDeAhorro(tipoDeCuenta, nombre, direccion, email, telefono, numeroCuentaInt, saldoDouble, cuentaAhorro.getNumeroCuenta())){
                           limpiarDatosDelaVista();
                           mensajeLabel.setText("Usuario registrado exitosamente");
                           mensajeLabel.setForeground(Color.BLUE);
                           MainView.dibujarUsuariosEnLaTabla();
                           //Hace falta que se muestre una retroalimentación en la vista para que el usuario 
                           //sepa que ya se registró la cuenta


                        }else{
                         mensajeLabel.setText("Error al registrar");
                         mensajeLabel.setForeground(Color.RED);
                       }
                    
                    }else{
                       /*
                        Como el número de cuenta viejo y nuevo no son iguales, 
                        tengo que revisar si no está repetido el nuevo número de cuenta
                        */
                       
                        if(!controlador.Controlador.numeroDeCuentaRepetido(numeroCuentaInt)){
                            if(controlador.Controlador.editarCuentaDeAhorro(tipoDeCuenta, nombre, direccion, email, telefono, numeroCuentaInt, saldoDouble, cuentaAhorro.getNumeroCuenta())){
                                limpiarDatosDelaVista();
                                mensajeLabel.setText("Usuario registrado exitosamente");
                                mensajeLabel.setForeground(Color.BLUE);
                                MainView.dibujarUsuariosEnLaTabla();
                                //Hace falta que se muestre una retroalimentación en la vista para que el usuario 
                                //sepa que ya se registró la cuenta


                            }else{
                              mensajeLabel.setText("Error al registrar");
                              mensajeLabel.setForeground(Color.RED);
                            }
                        
                        }else{
                
                            mensajeLabel.setText("Numero de cuenta repetido");
                            mensajeLabel.setForeground(Color.RED);
                        }
                    
                    }
                   
                }
              
        } catch (Exception e) {
            
        } 
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonActionPerformed
        
        JRadioButton radioButtonSelected =  (JRadioButton) evt.getSource();
        String textoDelRadioBotonSeleccionado  = radioButtonSelected.getText();
        
        desabilitarElementosDeLaVista();
        
        switch (textoDelRadioBotonSeleccionado) {
            case "Ahorro": ahorroRadioButton.setSelected(true); break;
            
            case "Crédito": 
                            creditoRadioButton.setSelected(true); 
                            interesMoratorioTextField.setEnabled(true);
                            limiteDeCreditoTextField.setEnabled(true);
                            interesMoratorioLabel.setEnabled(true);
                            limiteCreditoLabel.setEnabled(true);
                            break;
            
            case "Inversión": 
                            inversionRadioButton.setSelected(true); 
                            interesInversionTextField.setEnabled(true);
                            interesInversionLabel.setEnabled(true);
                            break;
            
        }
    }//GEN-LAST:event_radioButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
        
        if(registrarButton.getText().equals("Editar")){
       
         nombreTextField.setText(cuentaAhorro.getNombre());
         numeroCuentaTextField.setText(cuentaAhorro.getNumeroCuenta()+"");
         direccionTextField.setText(cuentaAhorro.getDireccion());
         telefonoTextField.setText(cuentaAhorro.getTelefono());
         emailTextField.setText(cuentaAhorro.getEmail());
         saldoTextField.setText(cuentaAhorro.getSaldo()+"");
         
       }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ahorroRadioButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JRadioButton creditoRadioButton;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel interesInversionLabel;
    private javax.swing.JTextField interesInversionTextField;
    private javax.swing.JLabel interesMoratorioLabel;
    private javax.swing.JTextField interesMoratorioTextField;
    private javax.swing.JRadioButton inversionRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel limiteCreditoLabel;
    private javax.swing.JTextField limiteDeCreditoTextField;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField numeroCuentaTextField;
    private javax.swing.JButton registrarButton;
    private javax.swing.JTextField saldoTextField;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables

    private void desabilitarElementosDeLaVista() {
        ahorroRadioButton.setSelected(false);
        inversionRadioButton.setSelected(false);
        creditoRadioButton.setSelected(false);
        
        interesInversionTextField.setEnabled(false);
        interesMoratorioTextField.setEnabled(false);
        limiteDeCreditoTextField.setEnabled(false);
        
        interesInversionLabel.setEnabled(false);
        interesMoratorioLabel.setEnabled(false);
        limiteCreditoLabel.setEnabled(false);
    }

    private void limpiarDatosDelaVista() {
        nombreTextField.setText("");
        numeroCuentaTextField.setText("");
        emailTextField.setText("");
        saldoTextField.setText("");
        direccionTextField.setText("");
        telefonoTextField.setText("");
        desabilitarElementosDeLaVista();
        ahorroRadioButton.setSelected(true);
    }
}
